# Dependencies
#markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Tanuj Kulshrestha
tagline:          'Personal Webpage'
description:      'Data Ebngineer</a>'
url:              http://2pforinterview.blogspot.in
baseurl:          /

author:
  name:           'Tanuj Kulshrestha'
  url:            https://facebook.com/sanchitalekh

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/tank113